# 06-03 · Zmiana kierunku

Praktyka do sekcji [„Zmuszamy żółwia do zmiany kierunku”](/pl/chapters/rozdzial-06/06-03-povorot-cherepashki.html).

## Cel

Opanuj absolutny kierunek: `setheading()`, `heading()`, `home()`.

## Ustawienie (wykonać raz)

In [1]:
import turtle

screen = turtle.Screen()
artist = turtle.Turtle()
artist.speed(0)
print("Окно Turtle готово.")

Окно Turtle готово.


## Sprawa robocza

In [2]:
artist.reset()
artist.setheading(90)
artist.forward(100)
artist.setheading(180)
artist.forward(100)
print("Курс:", artist.heading())

Курс: 180.0


## Eksperyment 1

Sprawdź kurs dla wszystkich czterech kierunków: 0°, 90°, 180°, 270°.

In [3]:
artist.reset()
for ugol in [0, 90, 180, 270]:
    artist.setheading(ugol)
    artist.forward(60)
    print(f"Курс {ugol}° -> позиция {artist.position()}")

Курс 0° -> позиция (60.00,0.00)


Курс 90° -> позиция (60.00,60.00)


Курс 180° -> позиция (0.00,60.00)


Курс 270° -> позиция (-0.00,0.00)


## Eksperyment 2

`home()` przywraca żółwia do pierwotnego punktu i początkowego kursu jedną komendą.

In [4]:
artist.reset()
artist.setheading(45)
artist.forward(100)
print("До home():", artist.position(), artist.heading())

artist.home()
print("После home():", artist.position(), artist.heading())

До home(): (70.71,70.71) 45.0


После home(): (0.00,0.00) 0.0


## Typowy błąd

`left()`/`right()` zmieniają kurs *względem obecnego* oraz `setheading()` — wyznacza kurs *absolutnie*. Jeśli pomieszasz to, liczba nie będzie taka, jakiej się spodziewałem.

In [5]:
artist.reset()
artist.setheading(90)   # смотрим вверх
artist.left(90)         # ОТНОСИТЕЛЬНЫЙ поворот от 90 -> 180, а не setheading(90)!
print("Итоговый курс:", artist.heading(), "(вероятно, не то, что ожидали)")

Итоговый курс: 180.0 (вероятно, не то, что ожидали)


## Podstawowa praktyka zadań ★

Narysuj krzyż (plus) z czterech promieni wychodzących ze środka, używając `setheading()` dla każdej wiązki: 0°, 90°, 180°, 270°.

In [6]:
artist.reset()
for ugol in [0, 90, 180, 270]:
    artist.setheading(ugol)
    artist.forward(80)
    artist.backward(80)
print("Готово, финальная позиция:", artist.position())

Готово, финальная позиция: (0.00,0.00)


## Ukończenie (wykonaj raz, na samym końcu)

In [7]:
screen.bye()
print("Окно Turtle закрыто.")

Окно Turtle закрыто.
