# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-02", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Основной результат: число историй', lambda: kolichestvo_variantov == 5 * 5 * 4 * 5 * 4)
_record('Поведение: произведение двух размеров', lambda: poschitat_varianty([1, 2], ['a', 'b', 'c']) == 6)
_record('Крайний случай: пустая группа', lambda: poschitat_varianty([], [1]) == 0)

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-02", "passed": passed, "score": score, "checks": checks}
