# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-03", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Все девять пар присутствуют', lambda: len(ishody_vseh_par) == 9)
_record('Победа игрока', lambda: ishody_vseh_par[('камень', 'ножницы')] == 'игрок')
_record('Крайний случай: ничья', lambda: ishody_vseh_par[('бумага', 'бумага')] == 'ничья')

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-03", "passed": passed, "score": score, "checks": checks}
