# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-07", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('duplicates и обычный путь', lambda: zadanie_args.command == 'duplicates' and zadanie_args.root == Path('/home/anna/Photos'))
_record('Крайний случай: пробел в пути', lambda: razobrat_duplicates('/tmp/Photo Archive').root == Path('/tmp/Photo Archive'))

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-07", "passed": passed, "score": score, "checks": checks}
