# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-08", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('JPG нормализован', lambda: zadanie_info.extension == '.jpg' and zadanie_info.size == 2048 and zadanie_info.path.name == 'photo.JPG')
_record('Крайний случай: имя без suffix', lambda: opisat_fajl(Path('README'), 1).extension == '')

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-08", "passed": passed, "score": score, "checks": checks}
