# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-12", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Неизвестное расширение идёт в other', lambda: any(op.source.name == 'strannyj.xyz' and op.destination.parent.name == 'other' for op in plan2.operations))
_record('Крайний случай: upper-case PDF', lambda: any(op.source.name == 'REPORT.PDF' and op.destination.parent.name == 'documents' for op in plan_s_dopolnitelnym_fajlom('REPORT.PDF').operations))

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-12", "passed": passed, "score": score, "checks": checks}
