# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-17", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Изменённый байт меняет digest', lambda: digest_izmenennogo != hashlib.sha256(soderzhimoe).hexdigest())
_record('Замена байта на то же значение сохраняет digest', lambda: digest_posle_zameny(b'abc', 1, ord('b')) == hashlib.sha256(b'abc').hexdigest())

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-17", "passed": passed, "score": score, "checks": checks}
