# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-19", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Destination переопределён из TOML', lambda: nastrojki_minimalnye.destination == 'Sorted2')
_record('Отсутствующая таблица использует defaults', lambda: nastrojki_minimalnye.extensions == DEFAULT_EXTENSIONS)
_record('Новая books добавлена, defaults сохранены', lambda: config_iz_toml('[extensions]\nbooks = [".epub"]\n').extensions['books'] == ['.epub'] and config_iz_toml('[extensions]\nbooks = [".epub"]\n').extensions['documents'] == DEFAULT_EXTENSIONS['documents'])
_record('Существующая категория заменяется', lambda: config_iz_toml('[extensions]\ndocuments = [".md"]\n').extensions['documents'] == ['.md'])

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-19", "passed": passed, "score": score, "checks": checks}
