# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-10", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Пользовательское исключение', lambda: 'node_modules' in svoi_nastrojki.excluded_names())
_record('Обязательные исключения сохранены', lambda: {'Sorted', '.safesort'} <= svoi_nastrojki.excluded_names())
_record('Поведение на другом имени', lambda: 'build' in config_s_isklyucheniem('build').excluded_names())

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-10", "passed": passed, "score": score, "checks": checks}
