# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-14", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Три последовательных имени', lambda: [p.name for p in imena2] == ['photo.jpg', 'photo (1).jpg', 'photo (2).jpg'])
_record('Крайний случай: count=0', lambda: svobodnye_imena(Path('x.txt'), 0) == [])
_record('Имя без расширения', lambda: svobodnye_imena(Path('README'), 1)[0].name == 'README')

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-14", "passed": passed, "score": score, "checks": checks}
