# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-15", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Основной результат', lambda: uspeshnyh == 1)
_record('Крайний случай: пустой список', lambda: poschitat_uspeshnye([]) == 0)
_record('Два успешных элемента', lambda: poschitat_uspeshnye([{'completed': True}, {'completed': True}]) == 2)

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-15", "passed": passed, "score": score, "checks": checks}
