# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-11", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Новая категория работает', lambda: classify('.PPTX', svoi_kategorii) == 'presentations')
_record('Встроенная категория сохранена', lambda: classify('.pdf', svoi_kategorii) == 'documents')
_record('Исходные defaults не мутированы', lambda: 'presentations' not in DEFAULT_EXTENSIONS)

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-11", "passed": passed, "score": score, "checks": checks}
