# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-23", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Успешный разбор возвращает 0', lambda: kod_razbora(['apply', '/tmp/x']) == 0)
_record('--help является успешным SystemExit(0)', lambda: kod_razbora(['--help']) == 0)
_record('Некорректная команда ненулевая', lambda: kod_razbora(['zip', '/tmp/x']) != 0)
_record('Отсутствие подкоманды тоже ненулевое', lambda: kod_razbora([]) != 0)

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-23", "passed": passed, "score": score, "checks": checks}
