# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-23-22", {})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({"name": name, "passed": result})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
_record('Найдена только точная пара', lambda: imena_grupp == {frozenset({'a1.txt', 'a2.txt'})})
_record('Крайний случай: нет файлов', lambda: imena_duplicate_groups([]) == set())
_record('Крайний случай: уникальный файл', lambda: imena_duplicate_groups([FileInfo('x', 1, b'x')]) == set())

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{"lesson_id": "23-22", "passed": passed, "score": score, "checks": checks}
