#!/usr/bin/env python3
"""Build behavior-based browser graders for Chapter 23 practice tasks."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "site" / "practice" / "graders"

CHECKS: dict[str, list[tuple[str, str]]] = {
    "23-02": [
        ("Основной результат: число историй", "kolichestvo_variantov == 5 * 5 * 4 * 5 * 4"),
        ("Поведение: произведение двух размеров", "poschitat_varianty([1, 2], ['a', 'b', 'c']) == 6"),
        ("Крайний случай: пустая группа", "poschitat_varianty([], [1]) == 0"),
    ],
    "23-03": [
        ("Все девять пар присутствуют", "len(ishody_vseh_par) == 9"),
        ("Победа игрока", "ishody_vseh_par[('камень', 'ножницы')] == 'игрок'"),
        ("Крайний случай: ничья", "ishody_vseh_par[('бумага', 'бумага')] == 'ничья'"),
    ],
    "23-07": [
        ("duplicates и обычный путь", "zadanie_args.command == 'duplicates' and zadanie_args.root == Path('/home/anna/Photos')"),
        ("Крайний случай: пробел в пути", "razobrat_duplicates('/tmp/Photo Archive').root == Path('/tmp/Photo Archive')"),
    ],
    "23-08": [
        ("JPG нормализован", "zadanie_info.extension == '.jpg' and zadanie_info.size == 2048"),
        ("Крайний случай: имя без suffix", "opisat_fajl(Path('README'), 1).extension == ''"),
    ],
    "23-10": [
        ("Пользовательское исключение", "'node_modules' in svoi_nastrojki.excluded_names()"),
        ("Обязательные исключения сохранены", "{'Sorted', '.safesort'} <= svoi_nastrojki.excluded_names()"),
        ("Поведение на другом имени", "'build' in config_s_isklyucheniem('build').excluded_names()"),
    ],
    "23-11": [
        ("Новая категория работает", "classify('.PPTX', svoi_kategorii) == 'presentations'"),
        ("Встроенная категория сохранена", "classify('.pdf', svoi_kategorii) == 'documents'"),
        ("Исходные defaults не мутированы", "'presentations' not in DEFAULT_EXTENSIONS"),
    ],
    "23-12": [
        ("Неизвестное расширение идёт в other", "any(op.source.name == 'strannyj.xyz' and op.destination.parent.name == 'other' for op in plan2.operations)"),
        ("Крайний случай: upper-case PDF", "any(op.source.name == 'REPORT.PDF' and op.destination.parent.name == 'documents' for op in plan_s_dopolnitelnym_fajlom('REPORT.PDF').operations)"),
    ],
    "23-14": [
        ("Три последовательных имени", "[p.name for p in imena2] == ['photo.jpg', 'photo (1).jpg', 'photo (2).jpg']"),
        ("Крайний случай: count=0", "svobodnye_imena(Path('x.txt'), 0) == []"),
        ("Имя без расширения", "svobodnye_imena(Path('README'), 1)[0].name == 'README'"),
    ],
    "23-15": [
        ("Основной результат", "uspeshnyh == 1"),
        ("Крайний случай: пустой список", "poschitat_uspeshnye([]) == 0"),
        ("Два успешных элемента", "poschitat_uspeshnye([{'completed': True}, {'completed': True}]) == 2"),
    ],
    "23-17": [
        ("Изменённый байт меняет digest", "digest_izmenennogo != hashlib.sha256(soderzhimoe).hexdigest()"),
        ("Замена байта на то же значение сохраняет digest", "digest_posle_zameny(b'abc', 1, ord('b')) == hashlib.sha256(b'abc').hexdigest()"),
    ],
    "23-18": [
        ("Пустая пара образует группу", "any(g['size'] == 0 and {f.name for f in g['files']} == {'pustoj_a.txt', 'pustoj_b.txt'} for g in gruppy2)"),
        ("Один пустой файл не образует группу", "not any(g['size'] == 0 for g in find_duplicates(fajly + [FileInfo('one', 0, b'')]))"),
    ],
    "23-19": [
        ("Отсутствующая таблица использует defaults", "nastrojki_minimalnye.extensions == DEFAULT_EXTENSIONS"),
        ("Новая books добавлена поверх defaults", "config_iz_toml('[extensions]\\nbooks = [\".epub\"]\\n').extensions['documents'] == DEFAULT_EXTENSIONS['documents']"),
        ("Существующая категория заменяется", "config_iz_toml('[extensions]\\ndocuments = [\".md\"]\\n').extensions['documents'] == ['.md']"),
    ],
    "23-22": [
        ("Найдена только точная пара", "imena_grupp == {frozenset({'a1.txt', 'a2.txt'})}"),
        ("Крайний случай: нет файлов", "imena_duplicate_groups([]) == set()"),
        ("Крайний случай: уникальный файл", "imena_duplicate_groups([FileInfo('x', 1, b'x')]) == set()"),
    ],
    "23-23": [
        ("Успешный разбор возвращает 0", "kod_razbora(['apply', '/tmp/x']) == 0"),
        ("--help является успешным SystemExit(0)", "kod_razbora(['--help']) == 0"),
        ("Некорректная команда ненулевая", "kod_razbora(['zip', '/tmp/x']) != 0"),
    ],
}


def render(lesson_id: str, checks: list[tuple[str, str]]) -> str:
    rows = "\n".join(
        "_record(" + repr(name) + ", lambda: " + expression + ")"
        for name, expression in checks
    )
    return f'''# Generated by scripts/build_chapter23_graders.py. Do not edit by hand.
_cells = __cartesian__["cells"]
_task = _cells.get("task-{lesson_id}", {{}})
checks = []


def _record(name, predicate):
    try:
        result = bool(predicate())
    except Exception:
        result = False
    checks.append({{"name": name, "passed": result}})


_record("Task cell выполнена без исключения", lambda: bool(_task) and _task.get("ok", False))
{rows}

_passed_count = sum(1 for check in checks if check["passed"])
passed = _passed_count == len(checks)
score = round(100 * _passed_count / len(checks))
{{"lesson_id": "{lesson_id}", "passed": passed, "score": score, "checks": checks}}
'''


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for lesson_id, checks in sorted(CHECKS.items()):
        path = OUT / f"{lesson_id}.py"
        path.write_text(render(lesson_id, checks), encoding="utf-8")
        print(f"Записан grader: {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
