"""Единый источник правды для примеров Turtle в главе 7 — тот же принцип,
что и в chapter_06_examples.py: каждая запись EXAMPLES[name] — завершённый
код (import, screen/artist, команды рисования), БЕЗ финального
screen.exitonclick()/screen.bye(). scripts/build_chapter_07.py показывает
этот код читателю (дописывая exitonclick() для локального запуска), а
scripts/generate_chapter_07_outputs.py выполняет ЭТОТ ЖЕ код headless и
сохраняет реальный результат — код и картинка не могут разойтись, потому
что это буквально одна и та же строка.
"""

EXAMPLES: dict[str, str] = {
    # --- 07-01 · экран как графическая система ---
    "07-01-light-theme": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=500, height=360)\n'
        'screen.title("Cartesian Turtle Studio")\n'
        'screen.bgcolor("#F5F2FF")\n'
        'artist = turtle.Turtle()\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(3)\n'
        'artist.forward(150)\n'
    ),
    "07-01-dark-theme": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=500, height=360)\n'
        'screen.title("Cartesian Turtle Studio — Dark")\n'
        'screen.bgcolor("#0D0230")\n'
        'artist = turtle.Turtle()\n'
        'artist.pencolor("#B9A0FC")\n'
        'artist.pensize(3)\n'
        'artist.forward(150)\n'
    ),
    # --- 07-10 · colormode и цвет ---
    "07-10-rgb-swatches": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=460, height=200)\n'
        'screen.colormode(255)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n'
        'artist.penup()\n\n'
        'swatches = [\n'
        '    ((255, 0, 0), "red"),\n'
        '    ((0, 200, 0), "green"),\n'
        '    ((0, 0, 255), "blue"),\n'
        '    ((255, 210, 0), "yellow"),\n'
        ']\n'
        'x = -170\n'
        'for color, label in swatches:\n'
        '    artist.goto(x, 0)\n'
        '    artist.fillcolor(color)\n'
        '    artist.pencolor("#0D0230")\n'
        '    artist.pendown()\n'
        '    artist.begin_fill()\n'
        '    for _ in range(4):\n'
        '        artist.forward(70)\n'
        '        artist.left(90)\n'
        '    artist.end_fill()\n'
        '    artist.penup()\n'
        '    artist.goto(x, -25)\n'
        '    artist.write(label, font=("Arial", 12, "normal"))\n'
        '    x += 110\n'
    ),
    # --- 07-02 · настраиваем саму Turtle ---
    "07-02-turtle-config": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=260)\n'
        'artist = turtle.Turtle()\n\n'
        'artist.speed(3)\n'
        'artist.pensize(4)\n'
        'artist.pencolor("purple")\n'
        'artist.shape("turtle")\n'
        'artist.forward(150)\n'
    ),
    # --- 07-11 · pencolor vs fillcolor ---
    "07-11-pencolor-only": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=320)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(4)\n'
        'artist.pencolor("blue")\n\n'
        'for _ in range(4):\n'
        '    artist.forward(120)\n'
        '    artist.right(90)\n'
    ),
    "07-11-color-combined": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=320)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(4)\n'
        'artist.color("blue", "gold")\n\n'
        'artist.begin_fill()\n'
        'for _ in range(4):\n'
        '    artist.forward(120)\n'
        '    artist.right(90)\n'
        'artist.end_fill()\n'
    ),
    # --- 07-12 · speed/tracer/update ---
    "07-12-tracer-batch": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=420)\n'
        'screen.tracer(0)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n'
        'artist.pencolor("#5B24F9")\n\n'
        'for i in range(36):\n'
        '    artist.circle(80)\n'
        '    artist.right(10)\n'
        'screen.update()\n'
    ),
    # --- 07-03 · фигуры без линий, окружности, точки (light intro) ---
    "07-03-zalivka": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=320)\n'
        'artist = turtle.Turtle()\n'
        'artist.fillcolor("gold")\n\n'
        'artist.begin_fill()\n'
        'for _ in range(4):\n'
        '    artist.forward(100)\n'
        '    artist.right(90)\n'
        'artist.end_fill()\n'
    ),
    "07-03-okruzhnost": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=320)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#5B24F9")\n\n'
        'artist.circle(80)\n'
    ),
    "07-03-tochka": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=260, height=200)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n\n'
        'artist.dot(50, "red")\n'
    ),
    # --- 07-13 · геометрия окружности ---
    "07-13-circle-positive": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=320)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#5B24F9")\n\n'
        'artist.circle(80)\n'
    ),
    "07-13-circle-negative": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=320)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#DB2777")\n\n'
        'artist.circle(-80)\n'
    ),
    # --- 07-04 · дуги (expand) ---
    "07-04-arcs-labeled": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=460, height=460)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.hideturtle()\n\n'
        'arcs = [(60, "#5B24F9"), (90, "#DB2777"), (180, "#059669"), (270, "#D97706"), (360, "#0D0230")]\n'
        'for extent, color in arcs:\n'
        '    artist.penup()\n'
        '    artist.goto(0, 0)\n'
        '    artist.setheading(0)\n'
        '    artist.pendown()\n'
        '    artist.pencolor(color)\n'
        '    artist.pensize(3)\n'
        '    artist.circle(90, extent)\n'
        '    artist.penup()\n'
        '    artist.write(f"  {extent}°", font=("Arial", 11, "bold"))\n'
    ),
    # --- 07-14 · circle steps ---
    "07-14-steps-3": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=320, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#5B24F9")\n\n'
        'artist.circle(80, steps=3)\n'
    ),
    "07-14-steps-4": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=320, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#5B24F9")\n\n'
        'artist.circle(80, steps=4)\n'
    ),
    "07-14-steps-6": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=320, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#5B24F9")\n\n'
        'artist.circle(80, steps=6)\n'
    ),
    # --- 07-05 · штампы (expand) ---
    "07-05-stamps": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=460, height=200)\n'
        'artist = turtle.Turtle()\n'
        'artist.shape("circle")\n'
        'artist.color("#5B24F9")\n'
        'artist.penup()\n\n'
        'for _ in range(6):\n'
        '    artist.stamp()\n'
        '    artist.forward(60)\n'
    ),
    "07-05-clearstamps": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=460, height=200)\n'
        'artist = turtle.Turtle()\n'
        'artist.shape("circle")\n'
        'artist.color("#5B24F9")\n'
        'artist.penup()\n\n'
        'stamp_ids = []\n'
        'for _ in range(6):\n'
        '    stamp_ids.append(artist.stamp())\n'
        '    artist.forward(60)\n\n'
        'artist.clearstamp(stamp_ids[0])\n'
        'artist.clearstamp(stamp_ids[2])\n'
        'artist.clearstamp(stamp_ids[4])\n'
    ),
    # --- 07-06 · текст на экране ---
    "07-06-write-basic": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=200)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n\n'
        'artist.write("Привет, Turtle!", font=("Arial", 20, "normal"))\n'
    ),
    # --- 07-15 · выравнивание и шрифт ---
    "07-15-align": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=460, height=260)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n'
        'artist.penup()\n\n'
        'for y, align, text in [(60, "left", "left"), (0, "center", "center"), (-60, "right", "right")]:\n'
        '    artist.goto(0, y)\n'
        '    artist.dot(6, "#5B24F9")\n'
        '    artist.write(text, align=align, font=("Arial", 16, "normal"))\n'
    ),
    "07-15-font": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=220)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n'
        'artist.penup()\n\n'
        'artist.goto(-180, 40)\n'
        'artist.write("Arial 12 normal", font=("Arial", 12, "normal"))\n'
        'artist.goto(-180, -30)\n'
        'artist.write("Arial 26 bold", font=("Arial", 26, "bold"))\n'
    ),
    # --- 07-16 · текст + координатная система ---
    "07-16-coordinate-chart": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=460, height=460)\n'
        'artist = turtle.Turtle()\n'
        'artist.hideturtle()\n'
        'artist.speed(0)\n\n'
        'artist.penup()\n'
        'artist.goto(-180, 0)\n'
        'artist.pendown()\n'
        'artist.goto(180, 0)\n'
        'artist.penup()\n'
        'artist.goto(0, -180)\n'
        'artist.pendown()\n'
        'artist.goto(0, 180)\n\n'
        'artist.penup()\n'
        'for value in [-100, -50, 50, 100]:\n'
        '    artist.goto(value, 0)\n'
        '    artist.dot(6, "#5B24F9")\n'
        '    artist.goto(value, -20)\n'
        '    artist.write(str(value), align="center", font=("Arial", 11, "normal"))\n'
        '    artist.goto(0, value)\n'
        '    artist.dot(6, "#5B24F9")\n'
        '    artist.goto(15, value)\n'
        '    artist.write(str(value), font=("Arial", 11, "normal"))\n'
        'artist.goto(0, 0)\n'
        'artist.dot(8, "#0D0230")\n'
        'artist.goto(10, 6)\n'
        'artist.write("0", font=("Arial", 11, "normal"))\n'
    ),
    # --- 07-17 · черепашка как графический объект ---
    "07-17-shapes-gallery": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=560, height=180)\n'
        'artist = turtle.Turtle()\n'
        'artist.penup()\n'
        'artist.pencolor("#5B24F9")\n\n'
        'shapes = ["arrow", "turtle", "circle", "square", "triangle", "classic"]\n'
        'x = -220\n'
        'for shape_name in shapes:\n'
        '    artist.goto(x, 20)\n'
        '    artist.shape(shape_name)\n'
        '    artist.stamp()\n'
        '    artist.goto(x, -25)\n'
        '    artist.write(shape_name, align="center", font=("Arial", 10, "normal"))\n'
        '    x += 85\n'
    ),
    "07-17-shapesize": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=220)\n'
        'artist = turtle.Turtle()\n'
        'artist.shape("turtle")\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.penup()\n\n'
        'sizes = [(0.5, -140), (1, -20), (2, 140)]\n'
        'for factor, x in sizes:\n'
        '    artist.goto(x, 0)\n'
        '    artist.shapesize(factor, factor)\n'
        '    artist.stamp()\n'
    ),
    "07-17-tilt": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=220)\n'
        'artist = turtle.Turtle()\n'
        'artist.shape("arrow")\n'
        'artist.shapesize(3, 3)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.penup()\n\n'
        'artist.goto(-100, 0)\n'
        'artist.setheading(0)\n'
        'artist.stamp()\n\n'
        'artist.goto(100, 0)\n'
        'artist.tilt(45)\n'
        'artist.stamp()\n'
    ),
    # --- 07-18 · несколько черепашек ---
    "07-18-two-turtles": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=320)\n\n'
        'alice = turtle.Turtle()\n'
        'alice.color("#5B24F9")\n'
        'alice.shape("turtle")\n'
        'alice.penup()\n'
        'alice.goto(-100, -80)\n'
        'alice.pendown()\n'
        'alice.setheading(70)\n'
        'alice.forward(140)\n\n'
        'bob = turtle.Turtle()\n'
        'bob.color("#DB2777")\n'
        'bob.shape("turtle")\n'
        'bob.penup()\n'
        'bob.goto(100, -80)\n'
        'bob.pendown()\n'
        'bob.setheading(110)\n'
        'bob.forward(140)\n'
    ),
    # --- 07-19 · clone() ---
    "07-19-clone": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=320)\n\n'
        'original = turtle.Turtle()\n'
        'original.color("#5B24F9")\n'
        'original.penup()\n'
        'original.goto(0, -100)\n'
        'original.setheading(90)\n\n'
        'copy = original.clone()\n'
        'copy.color("#DB2777")\n\n'
        'original.pendown()\n'
        'original.left(30)\n'
        'original.forward(160)\n\n'
        'copy.pendown()\n'
        'copy.right(30)\n'
        'copy.forward(160)\n'
    ),
    # --- 07-20 · clear vs reset vs home ---
    "07-20-clear-effect": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=260)\n'
        'artist = turtle.Turtle()\n'
        'artist.pencolor("#5B24F9")\n\n'
        'for _ in range(4):\n'
        '    artist.forward(100)\n'
        '    artist.right(90)\n'
        'artist.penup()\n'
        'artist.goto(120, 80)\n'
        'artist.clear()\n'
        '# clear() стирает рисунок, но НЕ трогает позицию черепашки —\n'
        '# точка появится там же, куда мы её только что переместили\n'
        'artist.dot(14, "#DB2777")\n'
    ),
    "07-20-reset-effect": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=260)\n'
        'artist = turtle.Turtle()\n'
        'artist.pencolor("#5B24F9")\n\n'
        'for _ in range(4):\n'
        '    artist.forward(100)\n'
        '    artist.right(90)\n'
        'artist.penup()\n'
        'artist.goto(120, 80)\n'
        'artist.reset()\n'
        '# reset() стирает рисунок И возвращает черепашку в (0, 0) —\n'
        '# точка появится в начале координат, а не там, где мы были\n'
        'artist.dot(14, "#DB2777")\n'
    ),
    # --- 07-07 · мини-проект: окружность в квадрате (upgrade) ---
    "07-07-square-plan": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#5B24F9")\n\n'
        'razmer = 150\n'
        'artist.penup()\n'
        'artist.goto(-razmer / 2, -razmer / 2)\n'
        'artist.pendown()\n'
        'for _ in range(4):\n'
        '    artist.forward(razmer)\n'
        '    artist.left(90)\n'
    ),
    "07-07-circle-inscribed": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n\n'
        'razmer = 150\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.penup()\n'
        'artist.goto(-razmer / 2, -razmer / 2)\n'
        'artist.pendown()\n'
        'for _ in range(4):\n'
        '    artist.forward(razmer)\n'
        '    artist.left(90)\n\n'
        'artist.pencolor("#DB2777")\n'
        'artist.penup()\n'
        'artist.goto(0, -razmer / 2)\n'
        'artist.setheading(0)\n'
        'artist.pendown()\n'
        'artist.circle(razmer / 2)\n'
    ),
    "07-07-challenge-concentric": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.pensize(3)\n\n'
        'razmer = 150\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.penup()\n'
        'artist.goto(-razmer / 2, -razmer / 2)\n'
        'artist.pendown()\n'
        'for _ in range(4):\n'
        '    artist.forward(razmer)\n'
        '    artist.left(90)\n\n'
        'colors = ["#DB2777", "#059669", "#D97706"]\n'
        'for i, color in enumerate(colors):\n'
        '    radius = razmer / 2 - i * 20\n'
        '    artist.pencolor(color)\n'
        '    artist.penup()\n'
        '    artist.goto(0, -radius)\n'
        '    artist.setheading(0)\n'
        '    artist.pendown()\n'
        '    artist.circle(radius)\n'
    ),
    # --- 07-21 · мини-проект: часы без времени ---
    "07-21-clock-marks": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=420)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#0D0230")\n'
        'artist.pensize(3)\n\n'
        '# circle(150) центрирует круг в 150 px СЛЕВА от текущего курса —\n'
        '# поэтому стартуем на 150 ниже (0, -150), чтобы центр циферблата попал в (0, 0)\n'
        'artist.penup()\n'
        'artist.goto(0, -150)\n'
        'artist.pendown()\n'
        'artist.circle(150)\n\n'
        'for hour in range(12):\n'
        '    artist.penup()\n'
        '    artist.goto(0, 0)\n'
        '    artist.setheading(90 - hour * 30)\n'
        '    artist.forward(135)\n'
        '    artist.pendown()\n'
        '    artist.forward(15)\n'
        '    artist.penup()\n'
    ),
    "07-21-clock-full": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=420)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#0D0230")\n'
        'artist.pensize(3)\n\n'
        '# circle(150) центрирует круг в 150 px СЛЕВА от текущего курса —\n'
        '# поэтому стартуем на 150 ниже (0, -150), чтобы центр циферблата попал в (0, 0)\n'
        'artist.penup()\n'
        'artist.goto(0, -150)\n'
        'artist.pendown()\n'
        'artist.circle(150)\n\n'
        'for hour in range(12):\n'
        '    artist.penup()\n'
        '    artist.goto(0, 0)\n'
        '    artist.setheading(90 - hour * 30)\n'
        '    artist.forward(135)\n'
        '    artist.pendown()\n'
        '    artist.forward(15)\n'
        '    artist.penup()\n\n'
        'for hour, label in [(0, "12"), (3, "3"), (6, "6"), (9, "9")]:\n'
        '    artist.goto(0, 0)\n'
        '    artist.setheading(90 - hour * 30)\n'
        '    artist.forward(110)\n'
        '    artist.write(label, align="center", font=("Arial", 16, "bold"))\n\n'
        'artist.pensize(5)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.goto(0, 0)\n'
        'artist.setheading(90 - 12 * 30)\n'
        'artist.pendown()\n'
        'artist.forward(80)\n'
        'artist.penup()\n\n'
        'artist.pensize(3)\n'
        'artist.pencolor("#DB2777")\n'
        'artist.goto(0, 0)\n'
        'artist.setheading(90 - 2 * 30)\n'
        'artist.pendown()\n'
        'artist.forward(120)\n'
    ),
    # --- 07-22 · мини-проект: координатная мишень ---
    "07-22-target-infographic": (
        'import turtle\n'
        'import random\n\n'
        'random.seed(4)\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=420)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.hideturtle()\n\n'
        'rings = [(140, "#DC2626"), (100, "#FAFAFC"), (60, "#DC2626"), (20, "#FAFAFC")]\n'
        'for radius, color in rings:\n'
        '    artist.penup()\n'
        '    artist.goto(0, -radius)\n'
        '    artist.pendown()\n'
        '    artist.fillcolor(color)\n'
        '    artist.pencolor("#0D0230")\n'
        '    artist.begin_fill()\n'
        '    artist.circle(radius)\n'
        '    artist.end_fill()\n\n'
        'artist.penup()\n'
        'artist.goto(-160, 0)\n'
        'artist.pendown()\n'
        'artist.goto(160, 0)\n'
        'artist.penup()\n'
        'artist.goto(0, -160)\n'
        'artist.pendown()\n'
        'artist.goto(0, 160)\n\n'
        'artist.penup()\n'
        'for _ in range(6):\n'
        '    x = random.randint(-120, 120)\n'
        '    y = random.randint(-120, 120)\n'
        '    artist.goto(x, y)\n'
        '    artist.dot(10, "#059669")\n\n'
        'artist.goto(-190, 170)\n'
        'artist.write("Координатная мишень", font=("Arial", 13, "bold"))\n'
    ),
    # --- 07-08 · направление рисования (rewrite) ---
    "07-08-cw-ccw": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=560, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pensize(3)\n\n'
        '# circle(70) — центр на 70 px СЛЕВА от курса: старт ниже центра на 70,\n'
        '# чтобы сам круг встал вокруг (-150, 0), не упираясь в край окна\n'
        'artist.penup()\n'
        'artist.goto(-150, -70)\n'
        'artist.pendown()\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.circle(70)\n'
        'artist.penup()\n'
        'artist.goto(-150, 115)\n'
        'artist.write("circle(70)", align="center", font=("Arial", 13, "bold"))\n'
        'artist.goto(-150, 95)\n'
        'artist.write("против часовой (+)", align="center", font=("Arial", 11, "normal"))\n\n'
        '# circle(-70) — центр на 70 px СПРАВА от курса: старт выше центра на 70,\n'
        '# чтобы круг встал вокруг (150, 0) — симметрично первому\n'
        'artist.goto(150, 70)\n'
        'artist.pendown()\n'
        'artist.pencolor("#DB2777")\n'
        'artist.circle(-70)\n'
        'artist.penup()\n'
        'artist.goto(150, 115)\n'
        'artist.write("circle(-70)", align="center", font=("Arial", 13, "bold"))\n'
        'artist.goto(150, 95)\n'
        'artist.write("по часовой (-)", align="center", font=("Arial", 11, "normal"))\n'
    ),
    # --- 07-09 · мини-проект: смайлик (upgrade, staged) ---
    "07-09-smiley-face": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n\n'
        '# circle(100) центрирует круг в 100 px СЛЕВА от курса — стартуем на\n'
        '# 100 ниже (0, -100), чтобы лицо встало ровно по центру окна (0, 0)\n'
        'artist.penup()\n'
        'artist.goto(0, -100)\n'
        'artist.pendown()\n'
        'artist.fillcolor("yellow")\n'
        'artist.pencolor("#0D0230")\n'
        'artist.pensize(2)\n'
        'artist.begin_fill()\n'
        'artist.circle(100)\n'
        'artist.end_fill()\n'
    ),
    "07-09-smiley-eyes": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n\n'
        'artist.penup()\n'
        'artist.goto(0, -100)\n'
        'artist.pendown()\n'
        'artist.fillcolor("yellow")\n'
        'artist.pencolor("#0D0230")\n'
        'artist.pensize(2)\n'
        'artist.begin_fill()\n'
        'artist.circle(100)\n'
        'artist.end_fill()\n\n'
        'artist.penup()\n'
        'artist.goto(-35, 35)\n'
        'artist.pendown()\n'
        'artist.dot(20, "black")\n'
        'artist.penup()\n'
        'artist.goto(35, 35)\n'
        'artist.pendown()\n'
        'artist.dot(20, "black")\n'
    ),
    "07-09-smiley-final": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=340)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n\n'
        'artist.penup()\n'
        'artist.goto(0, -100)\n'
        'artist.pendown()\n'
        'artist.fillcolor("yellow")\n'
        'artist.pencolor("#0D0230")\n'
        'artist.pensize(2)\n'
        'artist.begin_fill()\n'
        'artist.circle(100)\n'
        'artist.end_fill()\n\n'
        'artist.penup()\n'
        'artist.goto(-35, 35)\n'
        'artist.pendown()\n'
        'artist.dot(20, "black")\n'
        'artist.penup()\n'
        'artist.goto(35, 35)\n'
        'artist.pendown()\n'
        'artist.dot(20, "black")\n\n'
        'artist.penup()\n'
        'artist.goto(-45, -25)\n'
        'artist.setheading(-60)\n'
        'artist.pendown()\n'
        'artist.pensize(4)\n'
        'artist.circle(55, 120)\n\n'
        'artist.hideturtle()\n'
    ),
}
