"""EXAMPLES for Chapter 12's real-Turtle-output pipeline (see
turtle_output_lib.py). Every entry is a complete runnable script — creates
`screen = turtle.Screen()` (exact name, required by the shared runner),
draws, and deliberately omits exitonclick()/bye() (added by the runner).

Chapter 12 is the project lab: these examples are the actual code shown on
each project page, captured for real rather than hand-drawn — the Christmas
tree, the five spiral variants, the fully-automated mandala and the Turtle
race carried over from the original six projects, plus the new Polygon
Studio (five side counts, one formula) and Grid/Pixel Art (nested-list
matrix rendered as squares) projects.
"""

EXAMPLES: dict[str, str] = {
    # --- проект 12-3: рождественская ёлка ---
    "12-elka": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=340, height=380)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.hideturtle()\n'
        'artist.pencolor("green")\n'
        'artist.fillcolor("green")\n\n'
        'yarusy = 4\n'
        'shirina = 120\n\n'
        'artist.penup()\n'
        'artist.goto(0, 100)\n'
        'artist.pendown()\n\n'
        'for yarus in range(yarusy):\n'
        '    artist.begin_fill()\n'
        '    artist.setheading(240)\n'
        '    artist.forward(shirina)\n'
        '    artist.setheading(0)\n'
        '    artist.forward(shirina)\n'
        '    artist.setheading(120)\n'
        '    artist.forward(shirina)\n'
        '    artist.end_fill()\n\n'
        '    artist.penup()\n'
        '    artist.setheading(270)\n'
        '    artist.forward(30)\n'
        '    artist.pendown()\n'
        '    shirina -= 20\n\n'
        'artist.pencolor("brown")\n'
        'artist.fillcolor("brown")\n'
        'artist.setheading(270)\n'
        'artist.penup()\n'
        'artist.forward(10)\n'
        'artist.pendown()\n'
        'artist.begin_fill()\n'
        'for _ in range(2):\n'
        '    artist.forward(40)\n'
        '    artist.right(90)\n'
        '    artist.forward(20)\n'
        '    artist.right(90)\n'
        'artist.end_fill()\n'
    ),
    # --- проект 12-4: пять вариаций спирали ---
    "12-spiral-square": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=480, height=480)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(2)\n\n'
        'dlina = 5\n'
        'for _ in range(60):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(90)\n'
        '    dlina += 3\n'
    ),
    "12-spiral-random": (
        'import turtle\n'
        'import random\n\n'
        'random.seed(4)\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=480, height=480)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#DB2777")\n'
        'artist.pensize(2)\n\n'
        'dlina = 5\n'
        'for _ in range(60):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(random.randint(80, 100))\n'
        '    dlina += 3\n'
    ),
    "12-spiral-triangle": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=480, height=480)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#059669")\n'
        'artist.pensize(2)\n\n'
        'dlina = 5\n'
        'for _ in range(60):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(120)\n'
        '    dlina += 3\n'
    ),
    "12-spiral-star": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=480, height=480)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(2)\n\n'
        'dlina = 5\n'
        'for _ in range(100):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(144)\n'
        '    dlina += 2\n'
    ),
    "12-spiral-circle": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=480, height=480)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#DB2777")\n'
        'artist.pensize(2)\n\n'
        'radius = 5\n'
        'for _ in range(60):\n'
        '    artist.circle(radius, 90)\n'
        '    radius += 3\n'
    ),
    # --- проект 12-5: сложная мандала со случайными цветами ---
    "12-mandala-slozhnaya": (
        'import turtle\n'
        'import random\n\n'
        'random.seed(11)\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=420, height=420)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n\n'
        'luchi = 36\n'
        'shag_ugla = 360 / luchi\n'
        'cveta = ["red", "orange", "purple", "blue", "green"]\n\n'
        'for i in range(luchi):\n'
        '    artist.pencolor(random.choice(cveta))\n'
        '    artist.setheading(i * shag_ugla)\n'
        '    artist.forward(150)\n'
        '    artist.circle(20)\n'
        '    artist.forward(-150)\n'
    ),
    # --- проект 12-6: гонка Turtle ---
    "12-gonka-turtle": (
        'import turtle\n'
        'import random\n\n'
        'random.seed(2)\n'
        'screen = turtle.Screen()\n'
        'screen.setup(500, 400)\n\n'
        'cveta = ["red", "blue", "green", "orange"]\n'
        'uchastniki = []\n\n'
        'for i, cvet in enumerate(cveta):\n'
        '    t = turtle.Turtle()\n'
        '    t.shape("turtle")\n'
        '    t.color(cvet)\n'
        '    t.penup()\n'
        '    t.goto(-200, i * 40 - 60)\n'
        '    uchastniki.append(t)\n\n'
        'finish_line = 200\n'
        'pobeditel = None\n\n'
        'while pobeditel is None:\n'
        '    for t in uchastniki:\n'
        '        t.forward(random.randint(1, 10))\n'
        '        if t.xcor() >= finish_line:\n'
        '            pobeditel = t.pencolor()\n'
        '            break\n'
    ),
    # --- проект: студия многоугольников (одна формула, разное число сторон) ---
    "12-polygon-3": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=300, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(3)\n\n'
        'storony = 3\n'
        'dlina = 110\n'
        'ugol = 360 / storony\n\n'
        'for _ in range(storony):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(ugol)\n'
    ),
    "12-polygon-4": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=300, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(3)\n\n'
        'storony = 4\n'
        'dlina = 90\n'
        'ugol = 360 / storony\n\n'
        'for _ in range(storony):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(ugol)\n'
    ),
    "12-polygon-5": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=300, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(3)\n\n'
        'storony = 5\n'
        'dlina = 75\n'
        'ugol = 360 / storony\n\n'
        'for _ in range(storony):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(ugol)\n'
    ),
    "12-polygon-6": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=300, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(3)\n\n'
        'storony = 6\n'
        'dlina = 65\n'
        'ugol = 360 / storony\n\n'
        'for _ in range(storony):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(ugol)\n'
    ),
    "12-polygon-8": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=300, height=300)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.pencolor("#5B24F9")\n'
        'artist.pensize(3)\n\n'
        'storony = 8\n'
        'dlina = 55\n'
        'ugol = 360 / storony\n\n'
        'for _ in range(storony):\n'
        '    artist.forward(dlina)\n'
        '    artist.right(ugol)\n'
    ),
    # --- проект: пиксельная графика по матрице (сердце) ---
    "12-grid-art-heart": (
        'import turtle\n\n'
        'screen = turtle.Screen()\n'
        'screen.setup(width=360, height=360)\n'
        'artist = turtle.Turtle()\n'
        'artist.speed(0)\n'
        'artist.hideturtle()\n'
        'artist.penup()\n\n'
        'picture = [\n'
        '    [0, 1, 0, 1, 0],\n'
        '    [1, 1, 1, 1, 1],\n'
        '    [1, 1, 1, 1, 1],\n'
        '    [0, 1, 1, 1, 0],\n'
        '    [0, 0, 1, 0, 0],\n'
        ']\n\n'
        'razmer = 40\n'
        'for row_index, row in enumerate(picture):\n'
        '    for col_index, value in enumerate(row):\n'
        '        if value == 1:\n'
        '            x = -100 + col_index * razmer\n'
        '            y = 100 - row_index * razmer\n'
        '            artist.goto(x, y)\n'
        '            artist.pendown()\n'
        '            artist.fillcolor("#DB2777")\n'
        '            artist.begin_fill()\n'
        '            for _ in range(4):\n'
        '                artist.forward(razmer)\n'
        '                artist.right(90)\n'
        '            artist.end_fill()\n'
        '            artist.penup()\n'
    ),
}
