# 06-03 · Меняем направление

Практика к разделу [«Заставляем черепашку менять направление»](../../site/chapters/glava-06/06-03-povorot-cherepashki.html).

## Цель

Освоить абсолютное направление: `setheading()`, `heading()`, `home()`.

## Настройка (выполнить один раз)

In [1]:
import turtle

screen = turtle.Screen()
artist = turtle.Turtle()
artist.speed(0)
print("Окно Turtle готово.")

Окно Turtle готово.


## Рабочий пример

In [2]:
artist.reset()
artist.setheading(90)
artist.forward(100)
artist.setheading(180)
artist.forward(100)
print("Курс:", artist.heading())

Курс: 180.0


## Эксперимент 1

Проверьте курс для всех четырёх сторон света: 0°, 90°, 180°, 270°.

In [3]:
artist.reset()
for ugol in [0, 90, 180, 270]:
    artist.setheading(ugol)
    artist.forward(60)
    print(f"Курс {ugol}° -> позиция {artist.position()}")

Курс 0° -> позиция (60.00,0.00)


Курс 90° -> позиция (60.00,60.00)


Курс 180° -> позиция (0.00,60.00)


Курс 270° -> позиция (-0.00,0.00)


## Эксперимент 2

`home()` возвращает черепашку в исходную точку и исходный курс одной командой.

In [4]:
artist.reset()
artist.setheading(45)
artist.forward(100)
print("До home():", artist.position(), artist.heading())

artist.home()
print("После home():", artist.position(), artist.heading())

До home(): (70.71,70.71) 45.0


После home(): (0.00,0.00) 0.0


## Типичная ошибка

`left()`/`right()` меняют курс *относительно текущего*, а `setheading()` — задаёт курс *абсолютно*. Если перепутать, фигура получится не той, что ожидалось.

In [5]:
artist.reset()
artist.setheading(90)   # смотрим вверх
artist.left(90)         # ОТНОСИТЕЛЬНЫЙ поворот от 90 -> 180, а не setheading(90)!
print("Итоговый курс:", artist.heading(), "(вероятно, не то, что ожидали)")

Итоговый курс: 180.0 (вероятно, не то, что ожидали)


## Задание ★ Базовая практика

Нарисуйте крест (плюс) из четырёх лучей, выходящих из центра, используя `setheading()` для каждого луча: 0°, 90°, 180°, 270°.

In [6]:
artist.reset()
for ugol in [0, 90, 180, 270]:
    artist.setheading(ugol)
    artist.forward(80)
    artist.backward(80)
print("Готово, финальная позиция:", artist.position())

Готово, финальная позиция: (0.00,0.00)


## Завершение (выполнить один раз, в самом конце)

In [7]:
screen.bye()
print("Окно Turtle закрыто.")

Окно Turtle закрыто.
